kind: ConfigMap
apiVersion: v1
metadata :
    name: unique-host
    labels :
      openpolicyagent.org/policy: rego
data :
  main: |
      package kubernetes.admission

      deny[msg] {
          some other_ns, other_ingress
          input.request.kind.kind == "Ingress"
          input.request.operation == "CREATE"
          host := input.request.object.spec.rules[_].host
          ingress := ingresses[other_ns][other_ingress]
          other_ns != input.request.namespace
          ingress.spec.rules[_].host == host
          msg := sprintf("invalid ingress host %q (conflicts with %v/%v)", [host, other_ns, other_ingress])
          }
