apiVersion: v1
kind: Pod
metadata:
  name: test-audit
spec:
  securityContext:
    seccompProfile:
      type: Localhost
      localhostProfile:                         # <path to custom JSON file>  relative to  /var/lib/kubelet/seccomp
                                                # mkdir -p /var/lib/kubelet/seccomp/profiles
                                                #  /var/lib/kubelet/seccomp/profiles/audit.json
                                                #  {
                                                #       "defaultAction": "SCMP_ACT_LOG"
                                                #  }
                                                #  $grep syscall /var/log/syslog
                                                #  $ grep -w 35 /usr/include/asm/unistd_64.h   => #define __NR_nanosleep 35
  containers:
  - command: ["bash", "-c", "echo 'I just made some syscalls' && sleep 100"]
    image: ubuntu
    name: ubuntu
    securityContext:
      allowPrivilegeEscalation: false

---
pod-definition.yaml


apiVersion: v1
kind: Pod
metadata:
  labels:
    run: amicontained
  name: amicontained
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
  - args:
    - amicontained
    image: r.j3ss.co/amicontained
    name: amicontained
    securityContext:
      allowPrivilegeEscalation: false

---

# Profile to reject all syscalls
# /var/lib/kubelet/seccomp/profiles/violation.json

{
  "defaultAction": "SCMP_ACT_ERRNO"
}

apiVersion: v1
kind: Pod
metadata:
  name: test-violation
spec:
  securityContext:
    seccompProfile:
      type: Localhost
      localhostProfile: profiles/violation.json
  containers:
  - command: ["bash", "-c", "echo 'I just made some syscalls' && sleep 100"]
    image: ubuntu
    name: ubuntu
  restartPolicy: Never
